export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header style={{
                    backgroundColor: 'lightblue',
                    padding: '2rem'
                }}>
                    <p>header</p>
                </header>

                {children}

                <footer style={{
                    backgroundColor: 'lightcoral',
                    padding: '2rem'
                }}>
                    <p>footer</p>
                </footer>
            </body>
        </html>
    )
}
