export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function AuthLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}

                <footer style={{
                    backgroundColor: 'lightcoral',
                    padding: '2rem'
                }}>
                    <p>footer but in auth</p>
                </footer>
            </body>
        </html>
    )
}
