import Link from "next/link"
import '../globals.css'

export const metadata = {
    title: {
        default: 'next.js tutorial - demo',
        template: '%s | demo',
    },
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header style={{
                    backgroundColor: 'lightblue',
                    padding: '2rem'
                }}>
                    <p>header</p>
                    <Link href={'/'}>Home</Link>
                </header>

                {children}

                <footer style={{
                    backgroundColor: 'lightcoral',
                    padding: '2rem'
                }}>
                    <p>footer</p>
                </footer>
            </body>
        </html>
    )
}
