import Link from "next/link"
import '../globals.css'
import { ErrorWrapper } from "./error-wrapper"

export const metadata = {
    title: {
        default: 'next.js tutorial - demo',
        template: '%s | demo',
    },
    description: 'Generated by Next.js',
}

export default function MainLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ErrorWrapper>
                    {children}
                </ErrorWrapper>
            </body>
        </html>
    )
}
